### ISSUE TITLE
Azure: Disconnect Lighthouse from customer subscription

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1243]
## Summary

As a cloudigrade user via sources, when I destroy my Azure source, I want cloudigrade to disconnect and terminate its relationship with my Azure subscription.

We currently establish trust between ours and the customer's Azure subscriptions via Lighthouse, but we never break that relationship. We need to figure out how to do that, and do it whenever the source is gone! (Just like destroying the AWS CloudTrail.)

## Acceptance Criteria

- [x] Ideally verify that deleting a source breaks our access to the customer's subscription
  - If this is not technically possible from our side, we must have explanations documented.
- [x] Verify answers are documented for the questions below
- [x] Verify we at least have instructions so that we as cloudigrade devs can disconnect our subs from each other so we can cleanly start over with sources.

## Assumptions and Questions

- Is this possible to perform from within our cloudigrade subscription?
- Do we have to reach into the customer's subscription somehow? Do we have enough access within our relationship to do that?
- Do we have to ask the customer to do something?
- Is the relationship effectively established forever and we just have to ignore their subscription?

**Comment by abellotti** [comment]
First, establishing the relationship between our cloudigrade azure account and the customer's tenant. In doing this development, I want to be able to work in the Ephemeral environments before anything is merged/pushed to stage/prod. 

Based on https://github.com/cloudigrade/cloudigrade/issues/1026#issuecomment-1010386770 Here are updated instructions to work in Ephemeral.

_Note_: Since we do not have access to Ephemeral externally, we need to manually upload the Microsoft.Template for lighthouse.

First define the AZURE environment variables to your enterprise app, i.e. <login>-personal-dev:

```
export AZURE_TENANT_ID = <Tenant/Directory Id of Cloudigrade - Ephemeral>
export AZURE_SUBSCRIPTION_ID = <Subscription ID of Cloudigrade Ephemeral>
export AZURE_CLIENT_ID = <Enterprise Application (Client) ID for <login>-personal-dev>
export AZURE_SP_OBJECT_ID = <Object ID of Enterprise Application for <login>-personal-dev>
export AZURE_CLIENT_SECRET = <Client Secret for the App Registration for <login>-personal-dev>
```

Next, deploy Cloudigrade to your Ephemeral namespace via the `poetry run ansible-playbook ... deployment/playbooks/manage-clowder.yml` command.

In the following examples, we first port forward 8000 to Cloudigrade and 8002 to Sources:

i.e. first fetch your cloudigrade-api and sources-api-svc pod names, then do the oc port forwards:

```
$ oc port-forward pod/cloudigrade-api-<ext> 8000:8000 &
$ oc port-forward pod/sources-api-svc-<ext> 8002:8000 &
```

We cannot use the sources app meta data to get the payload URI as that points to the stage template that includes the stage cloudigrade azure client id and such. We need to fetch the one we provide from the cloudigrade api running in Ephemeral:

```
$ curl localhost:8000/api/cloudigrade/v2/azure-offer-template/ | jq  \
        > cloudigrade_ephemeral_azure_offer_template.json
```

Next step is to login to the **Cloudigrade RH Directory1** tenant in Azure to establish the relationship:

- Login to portal.azure.com
- Switch directory to **Cloudigrade RH Directory1**
- Go to https://portal.azure.com/#create/Microsoft.Template
- click on `Build your own template in the editor`
- click on `Load file`
- browse to your folder and select the `cloudigrade_ephemeral_azure_offer_template.json`
- click Save
- click Review + Create

You'd see Validation passed:

![image](https://user-images.githubusercontent.com/5797328/179069622-3404a28a-eacb-490e-bcc5-d5e1a9a9ba95.png)

Deployment in progress:

![image](https://user-images.githubusercontent.com/5797328/179069705-a7e023ef-d401-4304-bdb5-aaaee54a4e51.png)

and finally the deployment completes:

![image](https://user-images.githubusercontent.com/5797328/179069789-7442bcef-165e-4de1-bede-9e0cdbe06a0e.png)

**Comment by abellotti** [comment]
Next step is to create the new source. We'll leverage the environment's AZURE_SUBSCRIPTION_ID and the port forwards.

We will need an account to use, let's pick 1234567, first create it in the cloudigrade-db in api_user, 
then do the bulk_create in sources:

```
cat - <<!END! | http http://localhost:8002/api/sources/v3.1/bulk_create "x-rh-sources-psk: thisMustBeEphemeralOrMinikube" "x-rh-sources-account-number: 1234567"
{
  "sources":[
    {
      "name":"lighthousetestsource",
      "source_type_name":"azure"
    }
  ],
  "authentications":[
    {
      "resource_type":"application",
      "resource_name":"cloud-meter",
      "username":"${AZURE_SUBSCRIPTION_ID}",
      "authtype":"lighthouse_subscription_id"
    }
  ],
  "applications":[
    {
      "source_name":"lighthousetestsource",
      "application_type_name":"cloud-meter"
    }
   ]
}
!END!
```

```
cat - <<!END! | http http://localhost:8002/api/sources/v3.1/bulk_create "x_rh_sources_psk: `get_sources_psk`" "x_rh_sources_account_number: `my_identity --account-number`"
{
  "sources":[
    {
      "name":"lighthousetestsource",
      "source_type_name":"azure"
    }
  ],
  "authentications":[
    {
      "resource_type":"application",
      "resource_name":"cloud-meter",
      "username":"${AZURE_SUBSCRIPTION_ID}",
      "authtype":"lighthouse_subscription_id"
    }
  ],
  "applications":[
    {
      "source_name":"lighthousetestsource",
      "application_type_name":"cloud-meter"
    }
   ]
}
!END!
```

**Comment by abellotti** [comment]
To manually delete a lighthouse subscription via the Azure SDK can be performed as follows:

- First thing to do is to find the correct ManagedService definition and assignment that lighthouse created for wiring up the Tenant (containing the managed resources, i.e. Cloudigrade RH Directory 1) to the Managing Tenant (i.e. the Service Provider like Cloudigrade - Ephemeral).

```
$ az managedservices definition list
```

This will give you the current ManagedServices definitions as follows:

```
[
  {
    "id": "/subscriptions/c2b810d4-e83c-4df5-a728-f1301dd78561/providers/Microsoft.ManagedServices/registrationDefinitions/362ac3b8-be3a-5d88-83f8-225804596ead",
    "name": "362ac3b8-be3a-5d88-83f8-225804596ead",
    "plan": null,
    "properties": {
      "authorizations": [
        {
          "principalId": "1e5c961c-6fcf-414d-b36c-0ee7f25086a2",
          "principalIdDisplayName": "cloudigrade-ephemeral",
          "roleDefinitionId": "acdd72a7-3385-48ef-bd42-f606fba81ae7"
        }
      ],
      "description": "",
      "managedByTenantId": "eb5ee39f-c5eb-4c3f-a2ef-4c1b71a63457",
      "managedByTenantName": "Cloudigrade - Ephemeral",
      "provisioningState": "Succeeded",
      "registrationDefinitionName": "cloudigrade-ephemeral"
    },
    "type": "Microsoft.ManagedServices/registrationDefinitions"
  },
  {
    "id": "/subscriptions/c2b810d4-e83c-4df5-a728-f1301dd78561/providers/Microsoft.ManagedServices/registrationDefinitions/abddd142-28b8-5a33-ae4f-99cf65948201",
    "name": "abddd142-28b8-5a33-ae4f-99cf65948201",
    "plan": null,
    "properties": {
      "authorizations": [
        {
          "principalId": "177f4825-85d2-4f5e-94f1-fffa1580d430",
          "principalIdDisplayName": "cloudigrade-stage",
          "roleDefinitionId": "acdd72a7-3385-48ef-bd42-f606fba81ae7"
        }
      ],
      "description": "",
      "managedByTenantId": "cf24ec31-bd7a-43f2-8b61-e3d671c4bb98",
      "managedByTenantName": "Cloudigrade - Stage",
      "provisioningState": "Succeeded",
      "registrationDefinitionName": "cloudigrade-stage"
    },
    "type": "Microsoft.ManagedServices/registrationDefinitions"
  }
]
```

From that list we need to get the `name` of the definition that pertains to our lighthouse subscription, in this case, we are interested in `362ac3b8-be3a-5d88-83f8-225804596ead` which wires up our Tenant as shown in the id ` "id": "/subscriptions/c2b810d4-e83c-4df5-a728-f1301dd78561/providers/Microsoft.ManagedServices/registrationDefinitions/362ac3b8-be3a-5d88-83f8-225804596ead",` the c2b8.... to the Ephemeral tenant via  "managedByTenantId": "eb5ee39f-c5eb-4c3f-a2ef-4c1b71a63457".

Next if you list the actual assignments:

```
$ az managedservices assignment list
```

You will notice the same name `362ac3b8-be3a-5d88-83f8-225804596ead` for the assignment.

Deleting the lighthouse subscription can then be performed as follows:

```
$ az managedservices assignment delete --assignment "362ac3b8-be3a-5d88-83f8-225804596ead"
$ az managedservices definition delete --assignment "362ac3b8-be3a-5d88-83f8-225804596ead"
```

```

**Comment by abellotti** [comment]
You can also delete the lighthouse subscription in the Azure portal as follows:

- Login to the Cloudigrade - Ephemeral Tenant
- Click on `My customers`
- Click on `Delegations` on the left side
- In the list of delegations, you'll find the one for the managed tenant `Cloudigrade RH Dir1`
- Click on the trash can icon on the right side of that line
- Click on `Yes` to remove the delegation

After a few seconds, the managed tenant `Cloudigrade RH Dir` will be gone from the Customers and Delegations pages

**Comment by infinitewarp** [comment]
We're calling this `blocked` since we are waiting of feedback via email from our contact at Microsoft.

**Comment by infinitewarp** [comment]
The Azure portal UI is a completely unreliable dumpster fire and behaves wildly differently from one day to the next, but I _think_ I've verified the expectations here through a variety of CLI commands including help from https://github.com/cloudigrade/cloudigrade/issues/1329#issuecomment-1249288583. 

🔥 🗑️ 🔥

**Comment by infinitewarp** [comment]
The Azure portal UI is a completely unreliable dumpster fire and behaves wildly differently from one day to the next, but I _think_ I've verified the expectations here through a variety of CLI commands including help from https://github.com/cloudigrade/cloudigrade/issues/1329#issuecomment-1249288583. 

🔥 🗑️ 🔥
