### ISSUE TITLE
Azure Lighthouse uniqueness = subscription ID + region

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1339]
## Summary

As a cloudigrade user, I want cloudigrade to meter my subscription in multiple regions. However, Azure allows me to select only one region during Lighthouse setup. So, I may need to create multiple sources for the same Azure subscription ID, each for a different region.

Currently, the AzureCloudAccount class has a unique constraint on subscription_id. If we proceed with this issue, we should add region_id (or region, whatever), drop the uniqueness from subscription_id, and create a composite uniqueness across subscription_id and region together.

## Acceptance Criteria

- [ ] Verify two sources with the same Azure subscription ID can coexist if they have different regions.
- [ ] Verify two sources with the same Azure subscription ID **cannot** coexist if they the same region.

## Assumptions and Questions

- **Important prereq**: Before making any code changes for this issue, we need to confirm our assumptions about how regions work with Lighthouse.
  - Can a Lighthouse defined in Region A also see and interact with resources that exist in Regions B and C?
  - Test this by creating and starting VMs in multiple different regions, go through the usual source/Lighthouse/etc. setup for one specific region, and observe cloudigrade's results when it gets lists of VMs for that customer tenant.
  - If cloudigrade sees and records information for VMs in **all** regions, then this issue is moot and needs no changes.
  - See also https://learn.microsoft.com/en-us/azure/lighthouse/overview#cross-region-and-cloud-considerations which suggest that Lighthouse should be region-less.
- Yes, it's very likely that agreeing to a Lighthouse offer means selecting exactly one region.
- As an alternative, would it be possible to tie the Lighthouse offer etc. to the customer's tenant/directory so we can get *all* of their subscriptions across *all* regions? See also https://github.com/cloudigrade/cloudigrade/issues/1346 and we should wait until that's done before starting this issue.
- Does anything need to change in sources-api itself?
- Do we even get the region when things are created? If not, how can we find the region during setup/enable so that we can record it to our models?
- Less important, but can we ask around to get a feel for how many customers are operating in multiple regions? Maybe check with Rich and Dan. If we don't have an answer to this question, that's okay. This one isn't a blocker. It's just a curiosity.

**Comment by BrittRH** [comment]
# Issue-1339 Azure Lighthouse uniqueness = subscription ID + region

## Assumptions

1. Can a Lighthouse defined in Region A also see and interact with resources that exist in Regions B and C?
   1. (ANSWER) Yes, since subscriptions are regionless and if the customer has provided cloudigrade with the access to the subscription, it will be able to see all resources regardless of what region those resources are in.
2. Does agreeing to a Lighthouse offer mean selecting exactly one region?
   1. (ANSWER) No, you're just choosing where the offer (aka resource) happens to live. As long as cloudigrade was given access to the subscription or specific resource groups, it will be able to see the resources (e.g. VMs/VMSS instances) regardless of where they themselves are placed.
3. Does anything need to change in the sources-api itself?
   1. (ANSWER)
4. Do we get region when things are created? 
   1. (ANSWER) When accessing the VMs/VMSS instances, the region is returned in the data, however, there is no region data associated with where the Service Provider (the offer that the customer enables) lives.

**Comment by infinitewarp** [comment]
Thanks for the summary notes. I think this comment plus our observations over the last couple weeks are good enough to call this issue closed with no required code changes.
