### ISSUE TITLE
Make dev environment in OpenShift

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#217]
As a developer, I want to be able to run cloudigrade in OpenShift so I don't have to fight with problematic things like SELinux and Docker on my local system.

## Acceptance Criteria 

- [x] Verify I can run cloudigrade and its dependencies entirely on my local system
  - [x] Verify that this works on macOS 10.12
  - [x] Verify that this works on recent Fedora with SELinux enabled
  - [ ] ~Verify that this works on RHEL7 with SELinux enabled~
- [x] Verify that the documentation for devs is updated

## Assumptions and Questions

- This builds on the work from https://github.com/cloudigrade/cloudigrade/issues/149
- We must not require developers to push out to a remote OpenShift cluster; there must remain a supported option for working locally.

**Comment by blentz** [comment]
We have two "dog-fooding" options for implementing this:
[oc cluster up](https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md)
[Minishift](https://www.openshift.org/minishift/)

We may be able to support both because the template file will run anywhere. The bulk of the work is likely to be documenting how to get the environment set up on each platform.

**Comment by ilyavw** [comment]
@blentz ideally we go with openshift since that'll get people used to the oc cli
