### ISSUE TITLE
Authenticate via web browser

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#237]
As an end user, I want to be able to log in via my browser so that I can access my data.

## Acceptance Criteria 

- [x] Verify user can log in using web browser.
- [x] Verify documentation is updated if necessary to explain how auth token/header works.
- [x] Verify documentation exists to explain how to authenticate.
- [x] Verify integration tests's issue exists (see https://github.com/cloudigrade/integrade/issues/22)

## Assumptions and Questions

- This assumes that SOMEHOW a regular, non-superuser user exists in the DB.
  - This leaves it to the developer of this story to inject that data and explain.
  - This could be just a SQL `INSERT` statement, use Django built-in admin, etc.
- This requires a basic working web client with a login form.
- This would be an excellent candidate for a first _real_ integration test.
- For the backend, please look at:
  - https://github.com/sunscrapers/djoser
  - https://github.com/Tivix/django-rest-auth
  - http://www.django-rest-framework.org/api-guide/authentication/
- If using a third-party framework gets additional functionality like user registration or password reset working as well, great! 👍

**Comment by noahl** [comment]
https://github.com/cloudigrade/cloudigrade/pull/280 has the backend code for this

**Comment by noahl** [comment]
Here's a demo for the backend-only PR: https://asciinema.org/a/SVspdvpVGWrzXnOp4HAY8k1uC

Since this is partial work and the verification criteria above don't really apply, here's what I did:

1. Create user

http post http://cloudigrade-myproject.127.0.0.1.nip.io/auth/users/create/ username=developer password=djoserpassword

2. Try to get user info

http get http://cloudigrade-myproject.127.0.0.1.nip.io/auth/me/

3. Try to list accounts (or any other protected API endpoint)

http get http://cloudigrade-myproject.127.0.0.1.nip.io/api/v1/account/

4. Login as user

http post http://cloudigrade-myproject.127.0.0.1.nip.io/auth/token/create/ username=developer password=djoserpassword

export AUTH='Authorization: Token ...'

5. Get user info

http get http://cloudigrade-myproject.127.0.0.1.nip.io/auth/me/ "${AUTH}"

6. List accounts

http get http://cloudigrade-myproject.127.0.0.1.nip.io/api/v1/account/ "${AUTH}"

7. Logout as user

http post http://cloudigrade-myproject.127.0.0.1.nip.io/auth/token/destroy/ "${AUTH}"

8. Try to get user info with old token

http get http://cloudigrade-myproject.127.0.0.1.nip.io/auth/me/ "${AUTH}"

9. Try to list accounts with old token

http get http://cloudigrade-myproject.127.0.0.1.nip.io/api/v1/account/ "${AUTH}"

10. (bonus command, not in demo) Delete user account

http post http://cloudigrade-myproject.127.0.0.1.nip.io/auth/users/delete/ "${AUTH}" current_password=djoserpassword

**Comment by noahl** [comment]
@cdcabrera I just merged the backend branch. This is now ready for frontend work!

**Comment by kdelee** [comment]
One concern I have is that anybody can create users. Worst case is that someone hammers the `auth/users/create/` endpoint to overload the server. It also seems to deviate from the original thought that users would have their accounts created for them.

**Comment by kdelee** [comment]
Two other concerns:

* As currently implemented, you can create a user account with no email. This seems wrong as the user will then have no recourse to change their password if they forget it.
* As currently implemented, a user can delete their account themselves. Will this destroy all dependent data? If we have decided to not allow them to delete cloud acccounts, it follows that they should not be able to delete their entire account.

**Comment by elyezer** [comment]
Created https://github.com/cloudigrade/integrade/issues/22 to track adding the integration tests. Currently it is blocked by this issue so when this is merged and deployed the integration tests can be written.

**Comment by ilyavw** [comment]
AC is verified, waiting on https://github.com/cloudigrade/frontigrade/pull/21 to merge before closing issue.

**Comment by ilyavw** [comment]
Closed. Thanks!
