### ISSUE TITLE
Research usability of SNS/SQS versus continuous log scraping

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#25]
What are the benefits of subscribing to SNS?

Time-box to an hour to consolidate @adberglund's thoughts and record them here.

**Comment by adberglund** [comment]
### Summary 
I am now in favor of using this setup. If we are going to direct customers’ CloudTrail logs to *our* S3 buckets, then this is a simple, integrated way to keep track of when new logs are available. 

When a new CloudTrail log is published to S3, SNS sends a notification out with a message that contains the S3 bucket, and the object key for the log file. SQS can subscribe to the notification, which just stores the message in a queue. Then you poll the queue, process the message, and download the log file from S3. 


##### Pros: 
A managed queue. This is a low-effort and simple way to know when new logs are published to S3. If we have a separate S3 bucket for each customer, this could consolidate information to a single point that we check

##### Cons: 
Additional network calls to poll the queue and then delete the message after we have processed it. SQS does not auto-delete the message that you read, you have to specifically make a delete call. 

##### Alternatives
We could just look in our S3 buckets regularly and look for new files since the last time we checked. As the number of buckets we have goes up, this may get unwieldy. 

###### Resources
[Configuring Amazon SNS Notifications for CloudTrail - AWS CloudTrail](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/configure-sns-notifications-for-cloudtrail.html)

and

[Tutorial: Subscribing an Amazon SQS Queue to an Amazon SNS Topic - Amazon Simple Queue Service](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-subscribe-queue-sns-topic.html)

for reference
