### ISSUE TITLE
Do not copy AMI if in same AWS region

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#31]
As a Doppler admin, I want to only copy AMIs when crossing AWS region boundaries so that I do not incur unnecessary IO.

## Acceptance Criteria 

- [ ] Verify that scanning an AMI within the same region does not copy AMI
- [ ] Verify that scanning an AMI outside the same region does copy AMI and cleans up afterwards

**Comment by kdelee** [comment]
Can you provide some more information about this copying behavior?
I looked at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/CopyingAMIs.html .
My eyebrows are a bit high at the moment because I don't know why doppler would be making any changes to the AWS account -- I thought we would only want to be READING data not doing any action that would require "...copy an instance store-backed AMI, the user must have the following Amazon S3 permissions: `s3:CreateBucket, s3:GetBucketAcl`, "
