### ISSUE TITLE
Investigate Azure audit logging

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#316]
It's time to start looking at Azure! Let's start with one of the most critical pieces for cloudigrade: instance activity audit logging. In AWS, we have CloudTrail which is _very_ broad in its collection of data, but it does get what we need. For this research spike, please read the docs and experiment with Azure web console and APIs to see what its equivalent service is like. If you do not find an equivalent service, document anything you encounter that might provide similar functionality for cloudigrade.

To be clear, we specifically want to know **when instances are powered on and off.** We will investigate more for other areas (like image inspection) later.

Please collaborate closely with @dozdowski when documenting your findings so that he may work with outsiders to better define people resourcing.                       

Output: Documented research findings (commented on this issue is fine for now) with explanation of how Azure can provide this functionality.

If you need a developer account for playing with Azure, please ask @infinitewarp.

Time box: 3 days

**Comment by abaiken** [comment]
After exploring Azure for the past few days, I believe that we will be able to use the Activity Log to gather information regarding when instances are powered on and off. The Azure Activity Log documents any write events that are taken on the resources within a subscription. These Activity Logs can be queried, exported as csv/json, and set up to trigger alerts. 

The logs are retained for 90 days and can be accessed in multiple ways. In the Azure dashboard, navigate to the `Monitor` tab located on the left-hand side bar. From here, select `Activity log` under the shared services section. This brings up the following screen: 

![screen shot 2018-06-08 at 11 33 17 am](https://user-images.githubusercontent.com/34656858/41182625-738ea42e-6b44-11e8-9b84-3aa04d801c4c.png)

A query can be created by selecting a value for each of the options. For example, if I wanted to know every administrative event at the informational level regarding Virtual Machines that happened over the last 24 hours, my query would look like the one above. The Activity Log allows you to save multiple queries so that you can reuse them as necessary. 

If you want to see the Activity Log regarding a specific machine, you can select the machine under the resource option. Additionally, you can navigate to the `All resources` tab. From here, select the machine of interest. This will pull up a list of options directly to the right including the `Activity log` tab. Selecting the `Activity log` tab should bring up the familiar screen from before but with the specific vm pre-selected as the resource. 

You can create an Activity Log Alert by defining the criteria against which the activity log events will be filtered. This will allow you to receive an alert when an event occurs that meets the specified conditions. I personally experimented with this using email alerts, but you can also create alerts via webhooks, Azure functions, and a couple of other cool things. This means that we will be able to receive a notification any time a vm is powered on/off/created/deleted. You can create the Activity Log Alert by selecting the `Monitor` tab on the left-hand side of the Azure dashboard. You can then click on the `Alerts (classic)` section underneath the shared services. From here you can select `Add activity log alert` which will bring up the following template. 

<img width="814" alt="screen shot 2018-06-08 at 5 42 40 pm" src="https://user-images.githubusercontent.com/34656858/41182657-8f334bbc-6b44-11e8-8fe8-841803d0636e.png">

and once you scroll: 

<img width="1126" alt="screen shot 2018-06-08 at 5 42 56 pm" src="https://user-images.githubusercontent.com/34656858/41182673-a4673d0e-6b44-11e8-8533-4a3207b5ba2b.png">



This allows you to specify the type of information that you would like to be notified of, as well as the method of notification (sms/email/webhook/Azure function/etc.). The ability to create Azure functions is not included in the `Free Trial` subscription of Azure. However, it looks like they could possibly be useful (I am still reading the documentation about them). 

It also appears that Azure revamped the Alerts in March, which is right above the `Alerts Classic` section. I read about this after I had already set up alerts using the classic method but I am going to mess around with it this weekend and see if it does anything drastically different. 

This is not a huge amount of information, but it contains possibilities of what we will be able to use. I am going to continue playing around with Azure this weekend so this comment will probably grow before Monday. 

Helpful Links:
——————
[Azure Activity Logs](https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-overview-activity-logs) 

[Azure Activity Log Alerts (classic)](https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-activity-log-alerts)

[Azure Activity Log Alerts (next gen)](https://azure.microsoft.com/en-us/blog/the-next-generation-of-azure-alerts-has-arrived/)

**Comment by ilyavw** [comment]
Thank you for the thorough documentation! Closed.
