### ISSUE TITLE
As a user, I can update my existing cloud accounts

### ISSUE THREAD

**Issue by kdelee** [cloudigrade/cloudigrade#333]
## Summary

As a user, I can update my existing cloud accounts, so if I want to rename my account, update the ARN, or (in the future) update the resource type, I can do that. 

## Acceptance Criteria

- [ ] Verify that I can update the name of a cloud account (once they have names)
- [ ] Verify that I can update the resource type
- [ ] Verify that I can update the ARN

Questions:
Can super users update other user's cloud accounts?

**Comment by infinitewarp** [comment]
As discussed previously with Dan, with the pilot the only thing a user should be able to update for their account is a custom display name field.

No one should be able to change the type or ARN because once they are created they are immutable. If it was possible to change either, that would break or invalidate any information we had gathered related to it.

**Comment by kdelee** [comment]
since https://github.com/cloudigrade/cloudigrade/issues/267 already covers updating the name I'm going to close this as a duplicate.
