### ISSUE TITLE
Investigate migrating to GitLab

### ISSUE THREAD

**Issue by ilyavw** [cloudigrade/cloudigrade#352]
Pending our demo last Friday it seems there is interest in moving from github, to gitlab. Before we do that we need to verify that all of our CI jobs can be converted to gitlab-ci, updates made in regards to pipelines, any kind of process changes that may be required when moving between zenhub and gitlab boards are well documented, and other tasks that I'm forgetting now that we'll surely capture in our refinement session.

Time box: 2 days

Output: Documented here next steps, whether that means "stay on github" or "paste these commands to update your remotes".

We accept that "project reporting" is different in GitLab. If an analog to everything isn't available from ZenHub to GitLab, that shouldn't be a total blocker; it should be a point of conversation with the team.

**Comment by kdelee** [comment]
In regards to pipelines and seperate environments for different jobs, we also need a method to make sure any SQS queues can be purged/deleted between test runs.

Additionally, we may need to automate the creation of separate houndigrade clusters and s3 buckets for each environment.

**Comment by infinitewarp** [comment]
Whoever is interested in GitLab may also want to look at @ilyavw's prototype project for reference:

https://gitlab.com/xyzzy.sh/cloudigrade/blob/add-gitlab-ci/.gitlab-ci.yml

**Comment by elyezer** [comment]
My research was more on getting all current repos' `.travis.yml` converted to `.gitlab-ci.yml` than exercising the issue tracker and agile board. That said, the brief look I too on the issue tacker and agile board they look almost the same as we have with github issues + ZenHub, the difference is that on Gitlab we will view everything on the same UI.

To do the migration I would recommend create a window of ~2 hours (I expect only 1 hour or less but let's be safe) without any action done on Github for any of the repositories inside the Cloudigrade organization.

Next we need to delete and re-import all Cloudigrade organization's repositories into Gitlab. After that we need to create the `.gitlab-ci.yml` for each repo, here https://gist.github.com/elyezer/c0e8b359cec5b1c069c543876c040122 are the converted `.travis.yml` to `.gitlab-ci.yml`. In addition to adding the `.gitlab-ci.yml` we need to set the environment variables for each repo, specially the codecov token. These environment variables were captured in a document and are ready to be set.

Finally we can update our local clones' remote to point to Gitlab instead of Github. Run the following command inside every cloned repository that you want to update the remote URL to Gitlab:

```console
$ git remote set-url origin "$(git remote get-url origin | sed "s/github/gitlab/")"
```

Replace `origin` to the remote name on your local clone that points to Github.

If you use the same email for both Github and Gitlab than you are all set. If you are using a different email for Gitlab than you can configure it locally to the repository by running the below command inside each repository:

```console
$ git config user.email new@email.com
```

**Comment by elyezer** [comment]
You can check the Gitlab CI pipelines for each repo by accessing https://gitlab.com/cloudigrade/<repo>/pipelines, for example, https://gitlab.com/cloudigrade/integrade/pipelines

**Comment by infinitewarp** [comment]
Since we have all reviewed these notes and agreed to actually perform the GitLab migration today, I am closing this issue.

![](http://nitku.net/blog/blogcontent/uploads/2015/10/point-of-no-return.jpg)
