### ISSUE TITLE
If cloudtrail is deleted/dissapears, or if our policy gets broken, bad/undefined things happen

### ISSUE THREAD

**Issue by kdelee** [cloudigrade/cloudigrade#388]
## Summary

After account creation, if something happens to the cloud trail (deleted, renamed, etc...) we will never know, we will simply stop getting events and think everything is OK.

## Steps to Reproduce

1. Create user account
1. Create a cloud account for user
1. Observe that cloudtrail is set up in the cloud account
1. Delete the cloud trail
1. Notice that cloudigrade is happily unaware

## Expected Result

- cloudtrail is revived or some warning is placed on the cloud account `!!!!! warning !!!!! broken !!!!!!`

## Actual Result

- Nothing happens, could result in any instances that were last reported as being `POWERED ON` "spinning the meter". Also would result in missing any new instances. Silent failure.

## Additional context

While we can claim "this is an unsupported activity", we should be relatively resilient to errors like this that could precipitate from users banging around in their own AWS accounts living their AWS lives. It is entirely conceivable that they will mess the cloudtrail up. This could precipitate from them not paying attention to the disclosure that CloudTrail would be automagically configured, confusion if there are multiple people on an account mucking around, or if they ever do anything fast and loose with the AWS API.

**Comment by infinitewarp** [comment]
In order to handle this use case, we'll probably need to build some kind of scheduled check (maybe once a day) into cloudigrade that polls AWS for each account to verify that the trail still exists.

As we're building that out, it probably makes sense also to verify the IAM policy at the same time. The customer could break the role or policy, and that would cause other things to break, and it probably makes sense to have an all-encompassing "account health" checker.

**Comment by kdelee** [comment]
updated title to track also wanting to check that the policy is still good
