### ISSUE TITLE
Do we care about authentication? What's the vision?

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#61]
Because the initial version of the API is completely public and unauthenticated and unauthorized, we need to have a discussion to figure out how to protect things or if we even care to.

Do we want to use Red Hat's LDAP/SAML thing? Or a local account system? Or integrate with something else? Or nothing at all.

**Comment by tgerla** [comment]
Some initial thoughts: maybe we can break down the various aspects of authentication and authorization into a couple different use case buckets to help understand the issues more clearly:

Customer access:

- Customer needs to log in and manage their account basics, set up IAM access for metering, and view reports.

Cloudigrade components:

- Log analyzers (1..n) and Instance image scanners (1..n) will need authorization to the message bus and the management API, and maybe each other.

Staff access:

- Staff will need to be able to log in and view some customer information for troubleshooting and support. We need to be careful here so that customer data is available only on a need-to-know basis--I think it would be a bad idea for all staff to have full access to all customer data.

For customer and staff access, I think that in the long term we will want to attach ourselves to the Insights auth infrastructure. For the short term, I wonder if we can begin by using a Django-based boilerplate authorization/authentication system to get something going?

For cloudigrade component communication, I am open to suggestions. I need to do some research on best practices for this problem--it would also be worth investigating what Insights is doing and mirror and/or borrow their architecture.

**Comment by tgerla** [comment]
I'm sitting in on the Quipucords sprint demo and they've got a lot of UI progress with auth already--I will find out what they're doing.

**Comment by tgerla** [comment]
Quipucords is using django.contrib.auth as a placeholder.

**Comment by ilyavw** [comment]
I would assume we'd be authenticating against some sort of Red Hat SAML provider, but having some concrete info on that would be great.

**Comment by infinitewarp** [comment]
I'm going to close this since we got the initial answer we needed. We can do further research on auth at a later date when it's time to start integrating with other tools.
