### ISSUE TITLE
SystemExit exception seen  while calling internal API "v1/cloudaccounts" in stage environment. 

### ISSUE THREAD

**Issue by paraggit** [cloudigrade/cloudigrade#818]
## Summary

While calling internal API  "v1/cloudaccounts" using turnpike service its intermittently throwing exception 'SystemExit'.
following are the  few occurrences of the exception.

- [SystemExit](https://sentry.io/organizations/cloudigrade/issues/2243616832/?referrer=slack)   
- [SystemExit](https://sentry.io/organizations/cloudigrade/issues/2236298661/?referrer=slack)

## Steps to Reproduce

While calling following internal API using turnpike service this exception is intermittently hitting.

```shell 
(.iqe_venv)  % http -vv  --verify=false  --proxy="https:http://squid.corp.redhat.com:3128"  DELETE  https://internal.cloud.stage.redhat.com/api/cloudigrade/internal/api/cloudigrade/v1/cloudaccounts/641/  "Cookie:session=${STAGE_SESSION}"
```
```shell
DELETE /api/cloudigrade/internal/api/cloudigrade/v1/cloudaccounts/641/ HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 0
Cookie: session=8ee47ff3-0f20-49bb-a30b-0bd112e3fe69
Host: internal.cloud.stage.redhat.com
User-Agent: HTTPie/2.2.0



HTTP/1.1 504 Gateway Time-out
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 92
Content-Type: text/html
Date: Mon, 01 Mar 2021 08:44:08 GMT
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN

<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```

## Expected Result

- There should not be any exception get raised while calling internal API.

## Actual Result

- Exception get raised while calling internal API.

**Comment by infinitewarp** [comment]
I'm closing this issue since a timeout from the internal HTTP delete account API is a known problem but we are not supporting normal use of this internal API. The internal create and delete APIs are *not* intended for regular use or automation. They exist only for developers to have an alternate route into the system for local development where Kafka and sources-api are not available.

We may improve this behavior in https://github.com/cloudigrade/cloudigrade/issues/719 but that issue is a low priority.
